### ISSUE TITLE
tip: migrate to uv instead of pip install 

### ISSUE THREAD

**Issue by willwade** [ck-zhang/EyePy#6]
I reckon if you keep working on this your dependencies - particularly with mediapipe are going to be hell to manage. Look at migrating your dev setup to uv https://github.com/astral-sh/uv :)

**Comment by ck-zhang** [comment]
Good tip, but any reasons why mediapipe would be hard to manage?

**Comment by willwade** [comment]
well not mediapipe per se I guess - just once you start adding other dependencies we've found headaches come with py versions etc  - particularly cross platform (NB: UV is a dream. try it - you don't lose any of your regular requirements.txt stuff if you want it)
